version: '3'

networks:
  github-viewer:
    name: github-viewer

services:
  github-viewer-postgres:
    image: postgres
    hostname: github-viewer-postgres
    container_name: github-viewer-postgres
    ports: [ '5432:5432' ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github-viewer
    volumes: [ './db.sql:/docker-entrypoint-initdb.d/db.sql' ]
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      start_period: 10s
    networks:
      - github-viewer